// WARNING: Auto-generated — do not edit manually
// To update: yarn generate:colors

export type { ColorScale, ColorScaleWithModes, AccentColor, GrayColor } from './types'

export { tomato } from './tomato'
export { red } from './red'
export { ruby } from './ruby'
export { crimson } from './crimson'
export { pink } from './pink'
export { plum } from './plum'
export { purple } from './purple'
export { violet } from './violet'
export { iris } from './iris'
export { indigo } from './indigo'
export { blue } from './blue'
export { cyan } from './cyan'
export { teal } from './teal'
export { jade } from './jade'
export { green } from './green'
export { grass } from './grass'
export { bronze } from './bronze'
export { gold } from './gold'
export { brown } from './brown'
export { orange } from './orange'
export { amber } from './amber'
export { yellow } from './yellow'
export { lime } from './lime'
export { mint } from './mint'
export { sky } from './sky'
export { gray } from './gray'
export { mauve } from './mauve'
export { slate } from './slate'
export { sage } from './sage'
export { olive } from './olive'
export { sand } from './sand'
